### ISSUE TITLE
atom-text-editor.Object.defineProperty.get is deprecated.; Deprecated selector in `dbg/styles/debug.less`

### ISSUE THREAD

**Issue by ervinoro** [31i73/atom-dbg#10]
In `dbg/styles/debug.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .debug-breakpoint,
atom-text-editor::shadow .debug-breakpoint-hint` => `atom-text-editor.editor .debug-breakpoint,
atom-text-editor.editor .debug-breakpoint-hint`

* `atom-text-editor::shadow .debug-breakpoint:after,
atom-text-editor::shadow .debug-breakpoint-hint:after` => `atom-text-editor.editor .debug-breakpoint:after,
atom-text-editor.editor .debug-breakpoint-hint:after`

* `atom-text-editor::shadow .debug-breakpoint-hint` => `atom-text-editor.editor .debug-breakpoint-hint`

* `atom-text-editor::shadow .gutter[gutter-name="debug-gutter"]` => `atom-text-editor.editor .gutter[gutter-name="debug-gutter"]`

* `atom-text-editor::shadow .line-number.debug-position,
atom-text-editor::shadow .line-number.debug-position-error` => `atom-text-editor.editor .line-number.debug-position,
atom-text-editor.editor .line-number.debug-position-error`

* `atom-text-editor::shadow .line-number.debug-position:after,
atom-text-editor::shadow .line-number.debug-position-error:after` => `atom-text-editor.editor .line-number.debug-position:after,
atom-text-editor.editor .line-number.debug-position-error:after`

* `atom-text-editor::shadow .line-number.debug-position-error` => `atom-text-editor.editor .line-number.debug-position-error`

* `atom-text-editor::shadow .line-number.debug-position-error:after` => `atom-text-editor.editor .line-number.debug-position-error:after`

* `atom-text-editor::shadow .line.debug-position,
atom-text-editor::shadow .line.debug-position-error` => `atom-text-editor.editor .line.debug-position,
atom-text-editor.editor .line.debug-position-error`

* `atom-text-editor::shadow .line.debug-position-error` => `atom-text-editor.editor .line.debug-position-error`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
atom-text-editor.Object.defineProperty.get (/usr/share/atom/resources/app.asar/src/text-editor-element.js:68:18)
Object.installTextEditor (/home/ervion/.atom/packages/dbg/lib/main.coffee:289:42)
<unknown> (/home/ervion/.atom/packages/dbg/lib/main.coffee:220:21)
TextEditor.observeGrammar (/usr/share/atom/resources/app.asar/src/text-editor.js:608:7)
<unknown> (/home/ervion/.atom/packages/dbg/lib/main.coffee:218:60)
Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:329:9)
```

**Comment by ProPuke** [comment]
Cheers. @vanossj had just fixed this with #9 

Updated ver will be coming out shortly.
