### ISSUE TITLE
Issue with the buttons of the 'Configure Debug Session' panel

### ISSUE THREAD

**Issue by marcangels** [31i73/atom-dbg#11]
First, thanks for your amazing work !

I've find a little issue with the buttons of the 'Configure Debug Session' panel like you can see : 
![capture d ecran_2017-01-30_23-09-11](https://cloud.githubusercontent.com/assets/16955962/22444209/4b30eb9a-e742-11e6-9cdb-5665d8062a15.png)

I fix it in changing the debug.less file like it : 
`.input-block-item {
		display: flex;
		//flex: 1;
		padding: @component-padding / 2;
	}`

**Comment by ProPuke** [comment]
I believe this has been fixed by a recent update. Could you let me know if this still happens for you in the most recent version (in Atom 1.13+)?

If not I'll close this issue in a few days. Cheers

**Comment by marcangels** [comment]
Yes it is. Tanks for your answer :smiley:
