### ISSUE TITLE
Issue using gdb

### ISSUE THREAD

**Issue by DamSenViet** [31i73/atom-dbg#16]
When I attempted to debug a .py I got the following error message:

'gdb' is not recognized as an internal or external command,
operable program or batch file

I have the full 3 package set, running it on windows.

**Comment by vanossj** [comment]
My guess is that you do not have [gdb](https://www.gnu.org/software/gdb/) installed.

But even if you do install it, I don't think it this package will work for you.

The [dbg-gdb](https://atom.io/packages/dbg-gdb) atom package is intended for [gdb supported languages](https://sourceware.org/gdb/onlinedocs/gdb/Supported-Languages.html), which, unfortunately, python is not.

**Comment by ProPuke** [comment]
As @vanossj said - GDB is for statically compiled languages, like C or C++, not Python.

`dbg-gdb` also requires you to have `gdb` installed on your system.

Hopefully in the future we'll have a `dbg-python` module for python, too :D
