### ISSUE TITLE
New Docks API

### ISSUE THREAD

**Issue by pablomayobre** [31i73/atom-dbg#18]
I think this package should move to the new Docks API introduced in Atom 1.17 beta. This API allows users to move panels around and place them wherever they want or even minimise them, rearrange them and whatnot.

Information on this topics can be found mainly in the [latest post in the Atom blog](http://blog.atom.io/2017/04/12/atom-1-16.html)

**Comment by ProPuke** [comment]
Definitely! I've been waiting on this :]

**Comment by pablomayobre** [comment]
I corrected the information, the Docks API is available in 1.17 beta

**Comment by pablomayobre** [comment]
So fast! ❤️ Thanks for your work (applies to output-panel too)

PS: You should change the package.json so that this version of your package requires 1.17 or newer versions of Atom (or wait until 1.17 is released)
