### ISSUE TITLE
How to react to "cin" function or other input ones?

### ISSUE THREAD

**Issue by Kael-Chan** [31i73/atom-dbg#22]
when using atom-dbg on call of functions like cin, there's no method to enter uses data in it.
how to solve it ?
thank you~

**Comment by vanossj** [comment]
I have a pull request, 31i73/atom-dbg-gdb#16, for this.

But as a work around, you can connect a terminal window, outside of atom, to your debug application for standard IO.

### Linux (and Mac?)
 1. Open a terminal
_Note: you have to keep this terminal open, or you will have to update the tty path in the config file._
 2. Run the command `tty` you will get output the path to the terminal file, something like `/dev/pts/12`
 3. Create/Edit the [debug config](https://github.com/31i73/atom-dbg#debug-configuration-files) for your project. Add `"-tty=/dev/pts/12"` (match path from tty command) to `gdb_arguments`
#### example
```
"connect to term":
	debugger: 'dbg-gdb'
	path: "out"
	gdb_arguments: ["-tty=/dev/pts/12"]
````

### Windows
_not yet tested, but should work._
 1. Create/Edit the [debug config](https://github.com/31i73/atom-dbg#debug-configuration-files) for your project. Add `"set new-console on"` to `gdb_commands` array

#### example
```
"start new term":
	debugger: 'dbg-gdb'
	path: "out.exe"
	gdb_commands: ["set new-console on"]
````
