### ISSUE TITLE
lldb dbgProvider

### ISSUE THREAD

**Issue by dschwen** [31i73/atom-dbg#5]
Are there any plans for an lldb provider? It looks like that should be a fairly straight forward task. If there are no other takers I could have a look.

**Comment by ProPuke** [comment]
I did actually try building for lldb first, but ended up switching to gdb instead (I think I was still using MI in lldb, and it had a few compatibility issues, so gdb made more sense). GDB's "good-enough" for me atm, so I don't have plans.

Feel free if you want to tackle it :D
