### ISSUE TITLE
Variables are too hard to see

### ISSUE THREAD

**Issue by dcarrera** [31i73/atom-dbg#6]
When I run atom-dbg the names of the variables (in the "Variables" box) are nearly impossible to read because they are dark gray on a black background. The contrast is terrible and my eyes just cannot see the variable names. Is it possible to pick a different colour that better contrasts with the background?

In addition, the variables and the output box have a very small font size for me. I would like to see an option to increase the font size.

![screenshot](https://cloud.githubusercontent.com/assets/89128/21010642/7c6a2524-bd4d-11e6-856c-91adc8e59b1c.png)

**Comment by ProPuke** [comment]
Wow, that looks terrible in Atom Dark! Fixing...

**Comment by ProPuke** [comment]
Now fixed in current version.

I've enforced a hard-coded minimum font size, and ensured contrasting colours are always used on the sidebar. Should look better across different themes now.

Cheers

**Comment by dcarrera** [comment]
THANKS!!

It works great now.
